name: Deploy

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      # Run all cypress tests  
      - name: Cypress run with Cucumber
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          command: npx cypress run --browser chrome --headless
        continue-on-error: true
      # Upload a dummy artifact
      - name: Upload Dummy Artifact
        if: always()  # Run even if build failed
        uses: actions/upload-artifact@v2
        with:
          name: dummy-artifact
          path: /dev/null
  
  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  
      - name: Download Dummy Artifact
        if: always()  # Run even if build failed
        uses: actions/download-artifact@v2
        with:
          name: dummy-artifact
      - name: Copy Mochawesome Report
        run: cp cypress/reports/html/index.html $GITHUB_WORKSPACE/docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs  
          token: ${{ secrets.DEPLOY_TOKEN }}
