name: Deploy Mochawesome Report

on: [push]

permissions:
    contents: read
    pages: write
    id-token: write
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    # Install NPM dependencies, cache them correctly
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

    # Generates the mochawesome report and deploys it, making it accessible at:
    # https://<username>.github.io/<repository>/mochawesome-report (replace <username> and <repository> with your GitHub username and repository name)      
      - name: Generate Mochawesome Report
        run: |
              npx mochawesome-merge cypress/reports/html/.jsons/mochawesome.json > merged-report.json
              npx mochawesome-report-generator merged-report.json

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
